const FlowsEnums = Object.freeze({
  ONE_TIME: 'One Time',
  PERIODIC: 'Periodic',
  EVENT_TRIGERRED: 'Event Trigerred',
  ON_FLOW_EXIT: 'On Flow Exit',
  PAUSED: 'Paused',
  STOPPED: 'Stopped',
  RETIRED: 'Retired',
  ACTIVE: 'Active',
  SCHEDULED: 'Scheduled',
  COMPLETED: 'Completed',
  TODAY: 'Today',
  YESTERDAY: 'Yesterday',
  LAST_7_DAYS: 'Last 7 Days',
  THIS_WEEK: 'This Week',
  LAST_WEEK: 'Last Week',
  LAST_30_DAYS: 'Last 30 Days',
  THIS_MONTH: 'This Month',
  LAST_MONTH: 'Last Month',
  SINCE: 'Since',
  CUSTOM_RANGE: 'Custom Range',
  DETAILS_GOALS: 'details',
  FLOW_CONDITIONS: 'flow_conditions',
  TARGET_AUDIENCE: 'target_audience',
  ON_EVENT_TRIGGER: 'on_event_trigger',
  AT_FIXED_TIME: 'at_fixed_time',
  FLOW_EXIT: 'on_flow_exit',
  AT_SPECIFIC_DATE_TIME: 'at_specific_date_and_time',
  MODULE_NAME: 'flows',
});

export default FlowsEnums;
