require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/segmentations", type: :request do
  
  # Segmentation. As you add validations to Segmentation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Segmentation.create! valid_attributes
      get segmentations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      segmentation = Segmentation.create! valid_attributes
      get segmentation_url(segmentation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_segmentation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      segmentation = Segmentation.create! valid_attributes
      get edit_segmentation_url(segmentation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Segmentation" do
        expect {
          post segmentations_url, params: { segmentation: valid_attributes }
        }.to change(Segmentation, :count).by(1)
      end

      it "redirects to the created segmentation" do
        post segmentations_url, params: { segmentation: valid_attributes }
        expect(response).to redirect_to(segmentation_url(Segmentation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Segmentation" do
        expect {
          post segmentations_url, params: { segmentation: invalid_attributes }
        }.to change(Segmentation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post segmentations_url, params: { segmentation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested segmentation" do
        segmentation = Segmentation.create! valid_attributes
        patch segmentation_url(segmentation), params: { segmentation: new_attributes }
        segmentation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the segmentation" do
        segmentation = Segmentation.create! valid_attributes
        patch segmentation_url(segmentation), params: { segmentation: new_attributes }
        segmentation.reload
        expect(response).to redirect_to(segmentation_url(segmentation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        segmentation = Segmentation.create! valid_attributes
        patch segmentation_url(segmentation), params: { segmentation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested segmentation" do
      segmentation = Segmentation.create! valid_attributes
      expect {
        delete segmentation_url(segmentation)
      }.to change(Segmentation, :count).by(-1)
    end

    it "redirects to the segmentations list" do
      segmentation = Segmentation.create! valid_attributes
      delete segmentation_url(segmentation)
      expect(response).to redirect_to(segmentations_url)
    end
  end
end
