import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it } from '@jest/globals';
import AllS3SFTPList from 'containers/segments/s3-sftp-imports/AllS3SFTPList';
import { CustomWrapper } from 'test-utils';
import configureMockStore from 'redux-mock-store';

describe('AllS3SFTPList component', () => {
  const initialState = {
    s3sftpApp: {
      db_schedules: [
        {
          id: 62,
          end_type: 'After',
          frequency: 'monthly',
          import_name: 'ReegAudience Import Monthly',
          occurrences: 10,
          schedule_type: 'periodic',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'initiated',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'registered_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702109580,
          end_date: 0,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: '13 8 */ */1 *',
          occurrence_count: 0,
          repeat_every: 1,
          created_at: 1702109337,
          updated_at: 1702109337,
          run_at: 0,
          next_run_at: 1702109580,
        },
        {
          id: 61,
          end_type: '',
          frequency: null,
          import_name: 'processing check',
          occurrences: null,
          schedule_type: 'as_soon_as_possible',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'complete',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'anonymous_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702108162,
          end_date: 0,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: null,
          occurrence_count: 0,
          repeat_every: null,
          created_at: 1702108162,
          updated_at: 1702108346,
          run_at: 1702108162,
          next_run_at: 1702108162,
        },
        {
          id: 60,
          end_type: '',
          frequency: null,
          import_name: 'AnonymousCustom Attribute validation',
          occurrences: null,
          schedule_type: 'as_soon_as_possible',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'complete',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'anonymous_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702107224,
          end_date: 0,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: null,
          occurrence_count: 0,
          repeat_every: null,
          created_at: 1702107224,
          updated_at: 1702107404,
          run_at: 1702107224,
          next_run_at: 1702107224,
        },
        {
          id: 59,
          end_type: 'On',
          frequency: 'monthly',
          import_name: 'Regqausersmontly',
          occurrences: null,
          schedule_type: 'periodic',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'cancelled',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'registered_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702025820,
          end_date: 1704306600,
          deactivate: true,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: '57 8 */ */1 *',
          occurrence_count: 0,
          repeat_every: 1,
          created_at: 1702025675,
          updated_at: 1702043810,
          run_at: 0,
          next_run_at: 1702025820,
        },
        {
          id: 57,
          end_type: 'On',
          frequency: 'weekly',
          import_name: 'importweeklyref',
          occurrences: null,
          schedule_type: 'periodic',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'initiated',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'anonymous_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702025460,
          end_date: 1703010600,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: ['Monday', 'Tuesday', 'Sunday', 'Saturday'],
          cron_expression: '51 8  */7 * 1,2,0,6',
          occurrence_count: 0,
          repeat_every: 1,
          created_at: 1702025499,
          updated_at: 1702025499,
          run_at: 0,
          next_run_at: 1702025460,
        },
        {
          id: 56,
          end_type: 'On',
          frequency: 'daily',
          import_name: 'anonyperioduc',
          occurrences: null,
          schedule_type: 'periodic',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'processing',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'anonymous_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702025520,
          end_date: 1702319400,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: '52 8 */1 * *',
          occurrence_count: 0,
          repeat_every: 1,
          created_at: 1702025449,
          updated_at: 1702111930,
          run_at: 1702111930,
          next_run_at: 1702198320,
        },
        {
          id: 55,
          end_type: 'On',
          frequency: 'daily',
          import_name: 'regperiodictuesday',
          occurrences: null,
          schedule_type: 'periodic',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'processing',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'registered_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702025520,
          end_date: 1702319400,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: '52 8 */1 * *',
          occurrence_count: 0,
          repeat_every: 1,
          created_at: 1702025409,
          updated_at: 1702111930,
          run_at: 1702111930,
          next_run_at: 1702198320,
        },
        {
          id: 53,
          end_type: '',
          frequency: null,
          import_name: 'Regaudience at specifictie',
          occurrences: null,
          schedule_type: 'at_specific_time',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'complete',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'registered_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702025400,
          end_date: 0,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: null,
          occurrence_count: 0,
          repeat_every: null,
          created_at: 1702025277,
          updated_at: 1702025424,
          run_at: 1702025424,
          next_run_at: 1702025400,
        },
        {
          id: 51,
          end_type: '',
          frequency: null,
          import_name: 'Registered Audience Custom Attribute',
          occurrences: null,
          schedule_type: 'as_soon_as_possible',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'complete',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'registered_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1702020459,
          end_date: 0,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: null,
          occurrence_count: 0,
          repeat_every: null,
          created_at: 1702020459,
          updated_at: 1702020459,
          run_at: 1702020459,
          next_run_at: 1702020459,
        },
        {
          id: 50,
          end_type: '',
          frequency: null,
          import_name: 'AnonymousAudience955',
          occurrences: null,
          schedule_type: 'as_soon_as_possible',
          segment_name: null,
          connection_name: 'crm_database',
          source_type: 'database',
          source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
          status: 'complete',
          table_name: 'db_contacts',
          time_zone: 'Asia/Calcutta',
          import_type: 'anonymous_audience',
          email_ids: ['pratik_mishra1@persistent.com'],
          start_date: 1701973117,
          end_date: 0,
          deactivate: false,
          events_name: [],
          repeat_on_day_of_month: [],
          repeat_on_day_of_week: [],
          cron_expression: null,
          occurrence_count: 0,
          repeat_every: null,
          created_at: 1701973118,
          updated_at: 1701973298,
          run_at: 1701973119,
          next_run_at: 1701973117,
        },
      ],
      pagination: {
        current_page: 1,
        prev_page: null,
        next_page: 2,
        total_pages: 5,
        limit_value: 10,
        total_count: 46,
      },
    },
  };

  const mockState = configureMockStore();
  const store = mockState(initialState);

  const match = {
    url: '/app/accounts/6/segments/db-imports/list',
    path: '/app/accounts/6/segments/db-imports/list',
  };

  const commonProps = {
    item: [
      {
        id: 62,
        end_type: 'After',
        frequency: 'monthly',
        import_name: 'ReegAudience Import Monthly',
        occurrences: 10,
        schedule_type: 'periodic',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'initiated',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'registered_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702109580,
        end_date: 0,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: '13 8 */ */1 *',
        occurrence_count: 0,
        repeat_every: 1,
        created_at: 1702109337,
        updated_at: 1702109337,
        run_at: 0,
        next_run_at: 1702109580,
      },
      {
        id: 61,
        end_type: '',
        frequency: null,
        import_name: 'processing check',
        occurrences: null,
        schedule_type: 'as_soon_as_possible',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'complete',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'anonymous_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702108162,
        end_date: 0,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: null,
        occurrence_count: 0,
        repeat_every: null,
        created_at: 1702108162,
        updated_at: 1702108346,
        run_at: 1702108162,
        next_run_at: 1702108162,
      },
      {
        id: 60,
        end_type: '',
        frequency: null,
        import_name: 'AnonymousCustom Attribute validation',
        occurrences: null,
        schedule_type: 'as_soon_as_possible',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'complete',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'anonymous_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702107224,
        end_date: 0,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: null,
        occurrence_count: 0,
        repeat_every: null,
        created_at: 1702107224,
        updated_at: 1702107404,
        run_at: 1702107224,
        next_run_at: 1702107224,
      },
      {
        id: 59,
        end_type: 'On',
        frequency: 'monthly',
        import_name: 'Regqausersmontly',
        occurrences: null,
        schedule_type: 'periodic',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'cancelled',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'registered_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702025820,
        end_date: 1704306600,
        deactivate: true,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: '57 8 */ */1 *',
        occurrence_count: 0,
        repeat_every: 1,
        created_at: 1702025675,
        updated_at: 1702043810,
        run_at: 0,
        next_run_at: 1702025820,
      },
      {
        id: 57,
        end_type: 'On',
        frequency: 'weekly',
        import_name: 'importweeklyref',
        occurrences: null,
        schedule_type: 'periodic',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'initiated',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'anonymous_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702025460,
        end_date: 1703010600,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: ['Monday', 'Tuesday', 'Sunday', 'Saturday'],
        cron_expression: '51 8  */7 * 1,2,0,6',
        occurrence_count: 0,
        repeat_every: 1,
        created_at: 1702025499,
        updated_at: 1702025499,
        run_at: 0,
        next_run_at: 1702025460,
      },
      {
        id: 56,
        end_type: 'On',
        frequency: 'daily',
        import_name: 'anonyperioduc',
        occurrences: null,
        schedule_type: 'periodic',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'processing',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'anonymous_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702025520,
        end_date: 1702319400,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: '52 8 */1 * *',
        occurrence_count: 0,
        repeat_every: 1,
        created_at: 1702025449,
        updated_at: 1702111930,
        run_at: 1702111930,
        next_run_at: 1702198320,
      },
      {
        id: 55,
        end_type: 'On',
        frequency: 'daily',
        import_name: 'regperiodictuesday',
        occurrences: null,
        schedule_type: 'periodic',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'processing',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'registered_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702025520,
        end_date: 1702319400,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: '52 8 */1 * *',
        occurrence_count: 0,
        repeat_every: 1,
        created_at: 1702025409,
        updated_at: 1702111930,
        run_at: 1702111930,
        next_run_at: 1702198320,
      },
      {
        id: 53,
        end_type: '',
        frequency: null,
        import_name: 'Regaudience at specifictie',
        occurrences: null,
        schedule_type: 'at_specific_time',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'complete',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'registered_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702025400,
        end_date: 0,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: null,
        occurrence_count: 0,
        repeat_every: null,
        created_at: 1702025277,
        updated_at: 1702025424,
        run_at: 1702025424,
        next_run_at: 1702025400,
      },
      {
        id: 51,
        end_type: '',
        frequency: null,
        import_name: 'Registered Audience Custom Attribute',
        occurrences: null,
        schedule_type: 'as_soon_as_possible',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'complete',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'registered_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1702020459,
        end_date: 0,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: null,
        occurrence_count: 0,
        repeat_every: null,
        created_at: 1702020459,
        updated_at: 1702020459,
        run_at: 1702020459,
        next_run_at: 1702020459,
      },
      {
        id: 50,
        end_type: '',
        frequency: null,
        import_name: 'AnonymousAudience955',
        occurrences: null,
        schedule_type: 'as_soon_as_possible',
        segment_name: null,
        connection_name: 'crm_database',
        source_type: 'database',
        source_id: 'ba92a81a-ef5d-43b3-831b-b5bf069f344b',
        status: 'complete',
        table_name: 'db_contacts',
        time_zone: 'Asia/Calcutta',
        import_type: 'anonymous_audience',
        email_ids: ['pratik_mishra1@persistent.com'],
        start_date: 1701973117,
        end_date: 0,
        deactivate: false,
        events_name: [],
        repeat_on_day_of_month: [],
        repeat_on_day_of_week: [],
        cron_expression: null,
        occurrence_count: 0,
        repeat_every: null,
        created_at: 1701973118,
        updated_at: 1701973298,
        run_at: 1701973119,
        next_run_at: 1701973117,
      },
    ],
    currentPage: 1,
    totalPage: 10,
    onChangePage: jest.fn(),
  };
  it('render without crashing', () => {
    const { asFragment } = render(
      <CustomWrapper>
        <AllS3SFTPList match={match} {...commonProps} store={store} />
      </CustomWrapper>
    );
    expect(asFragment()).toMatchSnapshot();
  });
  it('render the component', () => {
    const { getByText } = render(
      <CustomWrapper>
        <AllS3SFTPList store={store} {...commonProps} />
      </CustomWrapper>
    );
    expect(getByText(/Name/i)).toBeInTheDocument();
  });

  it('click on the edit button', async () => {
    const { getByText } = render(
      <CustomWrapper>
        <AllS3SFTPList
          {...commonProps}
          getImportSchedulerByIdAction={jest.fn()}
        />
      </CustomWrapper>
    );
    expect(getByText(/Name/i)).toBeInTheDocument();
    const btn = screen.getByTestId('actionBtn62');
    fireEvent.click(btn);

    const actionBtn = screen.getByTestId('actionBtn62');
    fireEvent.click(actionBtn);

    await waitFor(() => {
      const editPopover = screen.getByTestId('PopOver62');
      fireEvent.click(editPopover);
    });

    const editBtn = screen.getByTestId('editBtn62');
    fireEvent.click(editBtn);
  });

  it('click on the Deactivate button', async () => {
    const { getByText } = render(
      <CustomWrapper>
        <AllS3SFTPList {...commonProps} />
      </CustomWrapper>
    );
    expect(getByText(/Name/i)).toBeInTheDocument();
    const btn = screen.getByTestId('actionBtn62');
    fireEvent.click(btn);

    const actionBtn = screen.getByTestId('actionBtn62');
    fireEvent.click(actionBtn);

    await waitFor(() => {
      const editPopover = screen.getByTestId('PopOver62');
      fireEvent.click(editPopover);
    });

    const deactivateBtn = screen.getByTestId('deactivateBtn62');
    fireEvent.click(deactivateBtn);
    await waitFor(() => {
      expect(getByText('Deactivate Database Import')).toBeInTheDocument();
      fireEvent.click(document.body);
      const closeBtn = screen.getByRole('button', {
        name: /Close/i,
      });
      fireEvent.click(closeBtn);
    });
  });
});
