json.id @email_config.id
json.account_id @email_config.account_id
json.email @email_config.email
json.forward_to_email @email_config.forward_to_email
json.created_at @email_config.created_at
json.updated_at @email_config.updated_at    
json.smtp_enabled @email_config.smtp_enabled
json.host_name @email_config.smtp_address
json.port @email_config.smtp_port
json.smtp_user_name @email_config.smtp_email
json.smtp_password @email_config.smtp_password
json.smtp_domain @email_config.smtp_domain
json.smtp_enable_starttls_auto @email_config.smtp_enable_starttls_auto
json.smtp_authentication @email_config.smtp_authentication
json.smtp_openssl_verify_mode @email_config.smtp_openssl_verify_mode
json.smtp_enable_ssl_tls @email_config.smtp_enable_ssl_tls
json.protocol @email_config.smtp_protocol
json.smtp_auth_enable @email_config.smtp_auth_enable
json.maximum_send_rate @email_config.maximum_send_rate
json.unsubscribe_setting @email_config.unsubscribe_setting
json.bounces_and_complaint_tracking @email_config.bounces_and_complaint_tracking      