ZERO = 0
ONE = 1
TWO = 2
THREE = 3
FOUR = 4
SEVEN = 7
TEN = 10
TWENTY = 20
NINETEEN = 19
FIFTY = 50
STATUS_ACTIVE = 'active'.freeze
STATUS_DRAFT = 'draft'.freeze
ACTION_SAVE_AS = 'save_as'.freeze
DIVIDED_WITH_TWO = 2
USER_PROPERTY = 'user_property'.freeze
CONTACTS = 'contacts'.freeze
USER_BEHAVIOR = 'user_behavior'.freeze
COMMON_EVENTS = 'common_events'.freeze
USER_AFFINITY = 'user_affinity'.freeze
USER_BEHAVIOR_ATTRIBUTES = 'user_behavior_attributes'.freeze
CONTACT_COMMON_EVENTS = 'contact_common_events'.freeze
USER_AFFINITY_ATTRIBUTES = 'user_affinity_attributes'.freeze
BATCH_SIZE = 5000
THREAD_BATCH_SIZE = 100
SAMPLE_USER_COUNT = 20
DIVIDED_WITH = 100.0
ROUNDOFF = 2
PERCENT_RESCUED = 0.0
USER = 'user'.freeze
ALL_USERS = 'All Users'.freeze
DOWNCASE_ALL_USERS = 'all_users'.freeze
CUSTOM_SEGMENTS = 'custom_segments'.freeze
USERS_IN_CUSTOM_SEGMENTS = 'Users in custom segment:'.freeze
FILE = 'File'.freeze
DAILY = 'daily'.freeze
MONTHLY = 'monthly'.freeze
AS_SOON_AS_POSSIBLE = 'as_soon_as_possible'.freeze
AT_SPECIFIC_TIME = 'at_specific_time'.freeze
PERIODIC = 'periodic'.freeze
EVENT_TRIGGER = 'event_trigger'.freeze
SMS_CAMPAIGN = "Campaign::SmsCampaign".freeze
EMAIL_CAMPAIGN = "Campaign::EmailCampaign".freeze
WHATSAPP_CAMPAIGN = "Campaign::WhatsappCampaign".freeze
SMTP_EMAIL = 'Smtp user name'.freeze
EMAIL_CAMPAIGN_SCOPE = 'with_emails'.freeze
SMS_CAMPAIGN_SCOPE = 'with_phone_number'.freeze
WHATSAPP_CAMPAIGN_SCOPE = 'with_phone_number'.freeze
INITIATED = 'initiated'
TATA_SMS_CHANNEL_TYPE =  'tata_smsc'.freeze
WHATSAPP_CHANNEL_TYPE = 'tata_whatsapp'.freeze
EMAIL_CHANNEL_TYPE = 'email'.freeze
RESPONSE_CODE_204 = '204'.freeze
WHATSAPP_CHANNEL_TYPE_TATA = 'whatsapp_tata_communications'.freeze
MAPPING_COLUMNS = {"customer_id": "integer", "email": "string", "phone_number": "string"}
ADD_USERS = 'add_users'.freeze
REPLACE_USERS = 'replace_users'.freeze
REMOVE_USERS = 'remove_users'.freeze
CONTACT_ATTRIBUTE = 'contact_attribute'.freeze
TEXT = 'text'.freeze
STATUS_DELIVERED = 'delivered'.freeze
CHANNEL_WHATSAPP = 'Channel::Whatsapp'.freeze
CHANNEL_SMS = 'Channel::TataSmsc'.freeze
CHANNEL_EMAIL = 'Channel::Email'.freeze
SMS = "SMS".freeze
WHATSAPP = "Whatsapp".freeze
EMAIL = "Email".freeze
AND = 'and'.freeze
DRAFT = 'draft'.freeze
PROCESSING = 'processing'.freeze
SCHEDULED = 'scheduled'.freeze
COMPLETED = 'completed'.freeze
FAILED = 'failed'.freeze
USER_DATA = '_user_data_'.freeze
BEGIN_RSA = '-----BEGIN RSA PRIVATE KEY-----'.freeze
END_RSA = '-----END RSA PRIVATE KEY-----'.freeze
DEFAULT_TIMEZONE = "Asia/Kolkata".freeze
UNDELIVERED = 'undelivered'.freeze
BOUNCED = 'bounced'.freeze
SENT = 'sent'.freeze
OPENED = 'opened'.freeze
EXPIRED = 'expired'.freeze
DELIVERED = 'delivered'.freeze
CLICKED = 'clicked'.freeze
ACCEPTED = 'accepted'.freeze
ROOT_DIR = "#{Rails.root}/tmp/crm_cdp/".freeze
CSV_PDF_EXCEL_HEADERS = ['Sr No.', 'Title', 'Created Date', 'Updated Date', 'Channel', 'Scheduling Type','Start Date', 'Status']
IMPORT_AUDIENCE = 'import_audience'.freeze
TIME_FORMAT = '%d %B %Y %I:%M:%S %P'
CUSTOM_ATTRIBUTES = 'custom_attributes'.freeze
READ = 'read'.freeze
MAIL_URL = "https://graph.microsoft.com/v1.0/users"
WHATSAPP_CLICKED = "WHATSAPP_MESSAGE_CLICKED".freeze
WHATSAPP_DELIVERED = "WHATSAPP_MESSAGE_DELIVERED".freeze
WHATSAPP_DELIVERY_FAILED = "WHATSAPP_MESSAGE_DELIVERY_FAILED".freeze
WHATSAPP_READ = "WHATSAPP_MESSAGE_READ".freeze
WHATSAPP_SENT = "WHATSAPP_MESSAGE_SENT".freeze
SMS_SENT = "SMS_SENT".freeze
SMS_DELIVERED = "SMS_DELIVERED".freeze
SYSTEM_FAILURE = 'system_failure'.freeze
VALID_URL_REGEXP = /^([w][w][w][.])|(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/.freeze
ANONYMOUS= 'anonymous'.freeze
REGISTERED= 'registered'.freeze
FAILED_TO_SEND = 'failed_to_send'.freeze
GENERIC_API_CALL_ERROR = 'generic_api_call_error'.freeze
TCL = 'tcl'.freeze
INVALID_MOBILE_NUMBER = 'invalid_mobile_number'.freeze
OTHER = 'other'.freeze
FAILED_TO_DELIVER = 'failed_to_deliver'.freeze
BLOCKED_FOR_USER = 'blocked_for_user'.freeze
PENDING_DELIVERY_CONFIRMATION = 'pending_delivery_confirmation'.freeze
UNKNOWN = 'unknown'.freeze
REJECTED= 'rejected'.freeze
FC_REJECTED = 'fc_rejected'.freeze
DND_REJECTED = 'dnd_rejected'.freeze
APPROVED = "APPROVED".freeze
EVENT = 'event'.freeze
EMAIL_BOUNCED = "EMAIL_BOUNCED".freeze
EMAIL_CLICKED = "EMAIL_CLICKED".freeze
EMAIL_COMPLAINED = "EMAIL_COMPLAINED".freeze
EMAIL_DROPPED = "EMAIL_DROPPED".freeze
EMAIL_OPENED = "EMAIL_OPENED".freeze
EMAIL_SENT = "EMAIL_SENT".freeze
EMAIL_SOFT_BOUNCED = "EMAIL_SOFT_BOUNCED".freeze
EMAIL_HARD_BOUNCED = "EMAIL_HARD_BOUNCED".freeze
EMAIL_UNSUBSCRIBE = "EMAIL_UNSUBSCRIBE".freeze
EMAIL_UNSUBSCRIBE_DROP = "EMAIL_UNSUBSCRIBE_DROP".freeze
EMAIL_VIEWED_IN_BROWSER = "EMAIL_VIEWED_IN_BROWSER".freeze
REQUESTS = "requests".freeze
BLOCKED = "blocked".freeze
SOFT_BOUNCED = "soft_bounced".freeze
UNSUBSCRIBE = "unsubscribe".freeze
DROPPED = "dropped".freeze
COMPLAINED = "complained".freeze
UNSUBSCRIBE_DROP = "unsubscribeDrop".freeze
VIEWED_IN_BROWSER = "viewedInBrowser".freeze
ACTIVE = "Active".freeze
EMAIL_DELIVERED = "EMAIL_DELIVERED".freeze
REGISTERED_AUDIENCE = "registered_audience".freeze
ANONYMOUS_AUDIENCE = "anonymous_audience".freeze
TATA_SMS_BASE_URL = ENV.fetch('TATA_SMSC_BASE_URL')
BASE_URL = ENV.fetch('BASE_URL').freeze
API_BASE_URL = ENV.fetch('API_BASE_URL').freeze
DB_IMPORT = 'db_import'.freeze
PHONE_NUMBER = 'phone_number'.freeze
WHATSAPP_DOWNCASE = 'whatsapp'.freeze
CURRENT_VERSION = 'current_version'.freeze
INITIAL_VERSION = 'initial_version'.freeze
FC_REJECTION_CODE = '601'.freeze
DND_REJECTION_CODE = '602'.freeze
INVALID_MOBILE_NUMBER_CODE = '333'.freeze
INVALID_EMAIL_ADDRESS = 'invalid_email_address'.freeze
WEEKLY = 'weekly'.freeze
WEEKDAYS_HASH = {"Sunday": 0, "Monday": 1, "Tuesday": 2, "Wednesday": 3, "Thursday": 4, "Friday": 5, "Saturday": 6}.as_json
COL_TYPES = {'string': 'text', 'text': 'text', 'integer': 'number', 'float': 'percent', 'datetime': 'date' }.as_json
NUMBER = 'number'.freeze
CSV_HEADERS = ['Sr No.', 'Customer Id']
PLATFORMS = %w(android ios web).freeze
CONFIG_TYPE_RULES = {
  'android' => {
    'private_key_file' => [],
    'fcm_server_key' => ['server_key', 'additional_server_key']
  },
  'ios' => {
    'apns_authentication_key' => ['team_id', 'key_id', 'bundle_id'],
    'apns_provider_certificate' => ['iphone_cert_password']
  },
  'web' => ['client_id', 'client_secret']
}.freeze
DEVICE = %w(iphone ipad mobile).freeze
NOTIFICATION_CHANNEL =  %w(mobile_push web_push).freeze
UTC = "UTC"
DEFAULT_BACKEND_PORT_NUMBER = 3050
CHANNEL_MAPPING = {
    'web_widget' => Channel::WebWidget,
    'api' => Channel::Api,
    'email' => Channel::Email,
    'line' => Channel::Line,
    'telegram' => Channel::Telegram,
    'viber' => Channel::Viber,
    'wechat' => Channel::Wechat,
    'kakao' => Channel::Kakao,
    'whatsapp' => Channel::Whatsapp,
    'sms' => Channel::Sms,
    'tatasmsc' => Channel::TataSmsc,
    'tata_smsc' => Channel::TataSmsc,
    'tata_whatsapp' => Channel::Whatsapp
}.freeze
CONTACT_SOCIAL_PROFILES = ['facebook', 'twitter', 'linkedin', 'github', 'telegram', 'whatsapp', 'instagram', 'youtube', 'pinterest', 'snapchat'].freeze
CONTACT_ADDITIONAL_ATTRIBUTES = ['bio', 'company_name', 'facebook', 'twitter', 'linkedin', 'github', 'telegram', 'whatsapp', 'instagram', 'youtube', 'pinterest', 'snapchat'].freeze
CONTACT_ATTRIBUTES = ['bio', 'company_name']
CAMPAIGN_CHANNEL = [{'id' => 'Email', 'value' => 'Email'}, {'id' => 'Sms', 'value' => 'Sms'}, {'id' => 'Whatsapp', 'value' => 'Whatsapp'}]
CAMPAIGN_TYPE = [{'id' => 'event_trigger', 'value' => 'Event Trigger'}, {'id' => 'one_time', 'value' => 'One Time'}, {'id' => 'periodic', 'value' => 'Periodic'}]
HARD_BOUNCED = "hard_bounced".freeze
BLOCKED = "blocked".freeze
DEFERRED = "deferred".freeze
LOADED_BY_PROXY = "loaded_by_proxy".freeze
