# DO NOT change the order of features EVER
- name: inbound_emails 
  enabled: true
- name: channel_email
  enabled: true
- name: channel_facebook
  enabled: true
- name: channel_telegram
  enabled: true
- name: channel_line
  enabled: true
- name: channel_kakao_talk
  enabled: true
- name: channel_wechat
  enabled: true
- name: channel_sms
  enabled: true
- name: channel_viber
  enabled: true
- name: channel_whatsapp
  enabled: true
- name: channel_twitter
  enabled: true
- name: ip_lookup
  enabled: false