import * as actions from 'redux/campaigns/actions';
import {
  CAMPAIGNS_GET,
  CAMPAIGNS_GET_SUCCESS,
  CAMPAIGNS_DELETE,
  CAMPAIGNS_DELETE_SUCCESS,
  CAMPAIGNS_DELETE_ERROR,
  CAMPAIGNS_DELETE_CLEAN,
  CAMPAIGNS_ADD,
  CAMPAIGNS_ADD_SUCCESS,
  CAMPAIGNS_ADD_ERROR,
  CAMPAIGNS_ADD_CLEAN,
  CAMPAIGNS_CREATE_TYPE_ADD,
  CAMPAIGNS_CREATE_TYPE_ADD_SUCCESS,
  CAMPAIGNS_CREATE_ADD,
  CAMPAIGNS_CREATE_ADD_SUCCESS,
  CAMPAIGNS_CREATE_ADD_ERROR,
  CAMPAIGNS_CREATE_ADD_CLEAN,
  SMS_CAMAPAIGNS_TEMPLATES_GET_ALL,
  SMS_CAMAPAIGNS_TEMPLATES_GET_ALL_SUCCESS,
  SMS_CAMAPAIGN_TEMPLATE_DELETE,
  SMS_CAMAPAIGN_TEMPLATE_DELETE_SUCCESS,
  SMS_CAMAPAIGN_TEMPLATE_DELETE_ERROR,
  SMS_CAMAPAIGN_TEMPLATE_DELETE_CLEAN,
  SMS_CAMAPAIGN_TEMPLATE_ADD,
  SMS_CAMAPAIGN_TEMPLATE_ADD_SUCCESS,
  SMS_CAMAPAIGN_TEMPLATE_ADD_ERROR,
  SMS_CAMAPAIGN_TEMPLATE_ADD_CLEAN,
  SMS_CAMAPAIGN_TEMPLATE_UPDATE,
  SMS_CAMAPAIGN_TEMPLATE_UPDATE_SUCCESS,
  SMS_CAMAPAIGN_TEMPLATE_UPDATE_ERROR,
  SMS_CAMAPAIGN_TEMPLATE_UPDATE_CLEAN,
  SCHEDULE_SMS_CAMPAIGN,
  SCHEDULE_SMS_CAMPAIGN_SUCCESS,
  SCHEDULE_SMS_CAMPAIGN_ERROR,
  SCHEDULE_SMS_CAMPAIGN_CLEAN,
  SMS_CAMAPAIGN_TAGS,
  SMS_CAMAPAIGN_TAGS_SUCCESS,
  SMS_CAMAPAIGNS_GET_ALL_SENDER_ID,
  SMS_CAMAPAIGNS_GET_ALL_SENDER_ID_SUCCESS,
  SMS_CAMAPAIGNS_GET_ALL_TEMPLATES_BASED_SENDER_ID,
  SMS_CAMAPAIGNS_GET_ALL_TEMPLATES_BASED_SENDER_ID_SUCCESS,
  SMS_CAMAPAIGNS_GET_ALL_TEMPLATES_BASED_SENDER_ID_ERROR,
  SMS_CAMAPAIGNS_GET_TEMPLATES_MESSAGE_BY_TEMPLATE_ID,
  SMS_CAMAPAIGNS_GET_TEMPLATES_MESSAGE_BY_TEMPLATE_ID_SUCCESS,
  SMS_CAMAPAIGNS_GET_TEMPLATES_MESSAGE_BY_TEMPLATE_ID_ERROR,
  GET_SMS_SEARCH_TEMPLATES,
  GET_SMS_SEARCH_TEMPLATES_SUCCESS,
  SMS_CONTENT_GENERATE_TINY_URL,
  SMS_CONTENT_GENERATE_TINY_URL_SUCCESS,
  SMS_CONTENT_GENERATE_PERSONALIZED_MSG,
  SMS_CONTENT_GENERATE_PERSONALIZED_MSG_SUCCESS,
  SET_WHATSAPP_CAMPAIGN_TEMPLATE_CATEGORY,
  SMS_CONTENT_GENERATE_PERSONALIZED_MSG_RESET,
  SMS_CAMAPAIGNS_GET_ALL_TEMPLATES_BASED_SENDER_ID_CLEAN,
  TEST_SMS_CAMPAIGN,
  TEST_SMS_CAMPAIGN_SUCCESS,
  TEST_SMS_CAMPAIGN_ERROR,
  TEST_SMS_CAMPAIGN_CLEAN,
  TEST_EMAIL_CAMPAIGN,
  TEST_EMAIL_CAMPAIGN_SUCCESS,
  TEST_EMAIL_CAMPAIGN_ERROR,
  TEST_EMAIL_CAMPAIGN_CLEAN,
  SMS_CAMPAIGN_SAVE_AS_DRAFT,
  SMS_CAMPAIGN_SAVE_AS_DRAFT_SUCCESS,
  SMS_CAMPAIGN_SAVE_AS_DRAFT_ERROR,
  SMS_CAMPAIGN_SAVE_AS_DRAFT_CLEAN,
  SMS_CAMPAIGN_UPDATE_STEP_INDEX,
  SMS_CAMPAIGN_NAME,
  FETCH_TEMPLATES_REQUEST,
  FETCH_TEMPLATES_SUCCESS,
  FETCH_TEMPLATES_FAILURE,
  FETCH_EMAIL_TEMPLATES_REQUEST,
  FETCH_EMAIL_TEMPLATES_SUCCESS,
  FETCH_EMAIL_TEMPLATES_FAILURE,
  GET_EMAIL_ADDRESS,
  GET_EMAIL_ADDRESS_SUCCESS,
  SET_SUBJECT,
  SET_PREVIEW_TEXT,
  SET_EMAIL_CONNECTOR,
  SET_SENDER_NAME,
  SET_FROM_EMAIL_ADDRESS,
  SET_REPLY_TO_EMAIL_ADDRESS,
  SET_CC,
  SET_BCC,
  SET_FORM_EMAIL_CREATION,
  SET_EMAIL_TARGET_AUDIENCE,
  RESET_SUCCESS,
  ADD_EMAIL_TEMPLATE,
  ADD_EMAIL_TEMPLATE_SUCCESS,
  ADD_EMAIL_TEMPLATE_FAILURE,
  ADD_EMAIL_TEMPLATE_ERROR_RESET,
  GET_EMAIL_TEMPLATE_BY_ID,
  EMAIL_TEMPLATE_ID,
  SET_DEFAULT_BTN,
  GET_WHATSAPP_CAMPAIGN_TEMPLATES_LIST_SUCCESS,
  GET_WHATSAPP_CAMPAIGN_TEMPLATES_LIST,
  GET_WHATSAPP_CAMPAIGN_DETAILED_TEMPLATES_LIST,
  TEST_WHATSAPP_CAMPAIGN,
  TEST_WHATSAPP_CAMPAIGN_SUCCESS,
  TEST_WHATSAPP_CAMPAIGN_ERROR,
  TEST_WHATSAPP_CAMPAIGN_CLEAN,
  CLEAR_CAMPAIGN_ON_TYPE_CHANGE,
  SET_CAMPAIGN_INBOX_ID,
  CLEAN_SELECTED_EMAIL_TEMPLATE,
  GET_CAMPAIGN_INFO_BY_ID,
  GET_CAMPAIGN_INFO_BY_ID_SUCCESS,
} from 'redux/constants';
import { describe, it, expect } from '@jest/globals';

describe('Channels Actions', () => {
  const item = {};

  it.each([
    [actions.getCampaigns, CAMPAIGNS_GET],
    [actions.getCampaignsSuccess, CAMPAIGNS_GET_SUCCESS],
    [actions.deleteCampaign, CAMPAIGNS_DELETE],
    [actions.deleteCampaignSuccess, CAMPAIGNS_DELETE_SUCCESS],
    [actions.deleteCampaignError, CAMPAIGNS_DELETE_ERROR],
    [actions.deleteCampaignClean, CAMPAIGNS_DELETE_CLEAN],
    [actions.addCampaign, CAMPAIGNS_ADD],
    [actions.addCampaignSuccess, CAMPAIGNS_ADD_SUCCESS],
    [actions.addCampaignError, CAMPAIGNS_ADD_ERROR],
    [actions.addCampaignClean, CAMPAIGNS_ADD_CLEAN],
    [actions.addCampaignCreateType, CAMPAIGNS_CREATE_TYPE_ADD],
    [actions.clearCampaignOnTypeChange, CLEAR_CAMPAIGN_ON_TYPE_CHANGE],
    [actions.addCampaignCreateTypeSuccess, CAMPAIGNS_CREATE_TYPE_ADD_SUCCESS],
    [actions.addCampaignCreate, CAMPAIGNS_CREATE_ADD],
    [actions.addCampaignCreateSuccess, CAMPAIGNS_CREATE_ADD_SUCCESS],
    [actions.addCampaignCreateError, CAMPAIGNS_CREATE_ADD_ERROR],
    [actions.addCampaignCreateClean, CAMPAIGNS_CREATE_ADD_CLEAN],
    [actions.getSmsCampaignsTemplatesAll, SMS_CAMAPAIGNS_TEMPLATES_GET_ALL],
    [
      actions.getSmsCampaignsTemplatesAllSuccess,
      SMS_CAMAPAIGNS_TEMPLATES_GET_ALL_SUCCESS,
    ],
    [actions.deleteSmsCampaignTemplate, SMS_CAMAPAIGN_TEMPLATE_DELETE],
    [
      actions.deleteSmsCampaignTemplateSuccess,
      SMS_CAMAPAIGN_TEMPLATE_DELETE_SUCCESS,
    ],
    [
      actions.deleteSmsCampaignTemplateError,
      SMS_CAMAPAIGN_TEMPLATE_DELETE_ERROR,
    ],
    [
      actions.deleteSmsCampaignTemplateClean,
      SMS_CAMAPAIGN_TEMPLATE_DELETE_CLEAN,
    ],
    [actions.addSmsCampaignTemplate, SMS_CAMAPAIGN_TEMPLATE_ADD],
    [actions.addSmsCampaignTemplateSuccess, SMS_CAMAPAIGN_TEMPLATE_ADD_SUCCESS],
    [actions.addSmsCampaignTemplateError, SMS_CAMAPAIGN_TEMPLATE_ADD_ERROR],
    [actions.addSmsCampaignTemplateClean, SMS_CAMAPAIGN_TEMPLATE_ADD_CLEAN],
    [actions.updateSmsCampaignTemplate, SMS_CAMAPAIGN_TEMPLATE_UPDATE],
    [
      actions.updateSmsCampaignTemplateSuccess,
      SMS_CAMAPAIGN_TEMPLATE_UPDATE_SUCCESS,
    ],
    [
      actions.updateSmsCampaignTemplateError,
      SMS_CAMAPAIGN_TEMPLATE_UPDATE_ERROR,
    ],
    [
      actions.updateSmsCampaignTemplateClean,
      SMS_CAMAPAIGN_TEMPLATE_UPDATE_CLEAN,
    ],
    [actions.testSmsCampaign, TEST_SMS_CAMPAIGN],
    [actions.testSmsCampaignSuccess, TEST_SMS_CAMPAIGN_SUCCESS],
    [actions.testSmsCampaignError, TEST_SMS_CAMPAIGN_ERROR],
    [actions.testSmsCampaignClean, TEST_SMS_CAMPAIGN_CLEAN],
    [actions.testEmailCampaign, TEST_EMAIL_CAMPAIGN],
    [actions.testEmailCampaignSuccess, TEST_EMAIL_CAMPAIGN_SUCCESS],
    [actions.testEmailCampaignError, TEST_EMAIL_CAMPAIGN_ERROR],
    [actions.testEmailCampaignClean, TEST_EMAIL_CAMPAIGN_CLEAN],
    [actions.scheduleSmsCampaign, SCHEDULE_SMS_CAMPAIGN],
    [actions.scheduleSmsCampaignSuccess, SCHEDULE_SMS_CAMPAIGN_SUCCESS],
    [actions.scheduleSmsCampaignError, SCHEDULE_SMS_CAMPAIGN_ERROR],
    [actions.getSmsCampaignsTagsSuccess, SMS_CAMAPAIGN_TAGS_SUCCESS],
    [actions.getAllSenderIdSuccess, SMS_CAMAPAIGNS_GET_ALL_SENDER_ID_SUCCESS],
    [
      actions.getAllTemplatesBasedOnSenderId,
      SMS_CAMAPAIGNS_GET_ALL_TEMPLATES_BASED_SENDER_ID,
    ],
    [
      actions.getAllTemplatesBasedOnSenderIdSuccess,
      SMS_CAMAPAIGNS_GET_ALL_TEMPLATES_BASED_SENDER_ID_SUCCESS,
    ],
    [
      actions.getAllTemplatesBasedOnSenderIdError,
      SMS_CAMAPAIGNS_GET_ALL_TEMPLATES_BASED_SENDER_ID_ERROR,
    ],
    [
      actions.getTemplatesMessageBasedOnTemplateId,
      SMS_CAMAPAIGNS_GET_TEMPLATES_MESSAGE_BY_TEMPLATE_ID,
    ],
    [
      actions.getTemplatesMessageBasedOnTemplateIdSuccess,
      SMS_CAMAPAIGNS_GET_TEMPLATES_MESSAGE_BY_TEMPLATE_ID_SUCCESS,
    ],
    [
      actions.getTemplatesMessageBasedOnTemplateIdError,
      SMS_CAMAPAIGNS_GET_TEMPLATES_MESSAGE_BY_TEMPLATE_ID_ERROR,
    ],
    [actions.getSearchSmsTemplates, GET_SMS_SEARCH_TEMPLATES],
    [actions.getSearchSmsTemplatesSuccess, GET_SMS_SEARCH_TEMPLATES_SUCCESS],
    [actions.generateTinyUrl, SMS_CONTENT_GENERATE_TINY_URL],
    [actions.generateTinyUrlSuccess, SMS_CONTENT_GENERATE_TINY_URL_SUCCESS],
    [actions.getPersonalizedMsg, SMS_CONTENT_GENERATE_PERSONALIZED_MSG],
    [
      actions.getPersonalizedMsgSuccess,
      SMS_CONTENT_GENERATE_PERSONALIZED_MSG_SUCCESS,
    ],
    [actions.setDefaultBtn, SET_DEFAULT_BTN],
    [actions.smsCampaignSaveAsDraft, SMS_CAMPAIGN_SAVE_AS_DRAFT],
    [actions.smsCampaignSaveAsDraftSuccess, SMS_CAMPAIGN_SAVE_AS_DRAFT_SUCCESS],
    [actions.smsCampaignSaveAsDraftError, SMS_CAMPAIGN_SAVE_AS_DRAFT_ERROR],
    [actions.smsCampaignSaveAsDraftClean, SMS_CAMPAIGN_SAVE_AS_DRAFT_CLEAN],
    [actions.updateStepIndex, SMS_CAMPAIGN_UPDATE_STEP_INDEX],
    [actions.setCampaignName, SMS_CAMPAIGN_NAME],
    [actions.fetchTemplatesSuccess, FETCH_TEMPLATES_SUCCESS],
    [actions.fetchTemplatesFailure, FETCH_TEMPLATES_FAILURE],
    [actions.fetchEmailTemplatesSuccess, FETCH_EMAIL_TEMPLATES_SUCCESS],
    [actions.fetchEmailTemplatesFailure, FETCH_EMAIL_TEMPLATES_FAILURE],
    [actions.getEmailAddress, GET_EMAIL_ADDRESS],
    [actions.getEmailAddressSuccess, GET_EMAIL_ADDRESS_SUCCESS],
    [actions.setSubject, SET_SUBJECT],
    [actions.setPreviewText, SET_PREVIEW_TEXT],
    [actions.setEmailConnector, SET_EMAIL_CONNECTOR],
    [actions.setSenderName, SET_SENDER_NAME],
    [actions.setFromEmailAddress, SET_FROM_EMAIL_ADDRESS],
    [actions.setReplyToEmailAddress, SET_REPLY_TO_EMAIL_ADDRESS],
    [actions.setCC, SET_CC],

    [actions.setBCC, SET_BCC],
    [actions.setFormEmailCreation, SET_FORM_EMAIL_CREATION],
    [actions.setEmailTargetAudience, SET_EMAIL_TARGET_AUDIENCE],
    [actions.addEmailTemplate, ADD_EMAIL_TEMPLATE],
    [actions.addEmailTemplateSuccess, ADD_EMAIL_TEMPLATE_SUCCESS],
    [actions.addEmailTemplateFailure, ADD_EMAIL_TEMPLATE_FAILURE],
    [actions.emailTemplateId, EMAIL_TEMPLATE_ID],
    [actions.getEmailTemplateById, GET_EMAIL_TEMPLATE_BY_ID],
    [
      actions.getWhatsAppCampaignTemplatesList,
      GET_WHATSAPP_CAMPAIGN_TEMPLATES_LIST,
    ],
    [
      actions.getWhatsAppCampaignTemplatesListSuccess,
      GET_WHATSAPP_CAMPAIGN_TEMPLATES_LIST_SUCCESS,
    ],
    [
      actions.getWhatsAppCampaignTemplatesListDetailed,
      GET_WHATSAPP_CAMPAIGN_DETAILED_TEMPLATES_LIST,
    ],
    [
      actions.setWhatsAppCampaignTemplateCategory,
      SET_WHATSAPP_CAMPAIGN_TEMPLATE_CATEGORY,
    ],
    [actions.testWhatsAppCampaign, TEST_WHATSAPP_CAMPAIGN],
    [actions.testWhatsAppCampaignSuccess, TEST_WHATSAPP_CAMPAIGN_SUCCESS],
    [actions.testWhatsAppCampaignError, TEST_WHATSAPP_CAMPAIGN_ERROR],
    [actions.testWhatsAppCampaignClean, TEST_WHATSAPP_CAMPAIGN_CLEAN],
    [actions.setCampaignInboxId, SET_CAMPAIGN_INBOX_ID],
    [actions.getCampaignInfoById, GET_CAMPAIGN_INFO_BY_ID],
    [actions.getCampaignInfoByIdSuccess, GET_CAMPAIGN_INFO_BY_ID_SUCCESS],
  ])('should create %p action', (actionCreator, expectedType) => {
    expect(actionCreator(item)).toEqual({
      type: expectedType,
      payload: item,
    });
  });

  it.each([
    [actions.cleanSelectedEmailTemplate, CLEAN_SELECTED_EMAIL_TEMPLATE],
    [actions.getAllSenderId, SMS_CAMAPAIGNS_GET_ALL_SENDER_ID],
  ])('should create &p action', (actionCreator, expectedType) => {
    expect(actionCreator()).toEqual({
      type: expectedType,
    });
  });
});
