import * as actions from 'redux/settingsChannels/actions';
import {
  SETTINGS_SMS_CHANNELS_GET,
  SETTINGS_SMS_CHANNELS_GET_SUCCESS,
  SETTINGS_SMS_CHANNELS_ADD_SUCCESS,
  SETTINGS_SMS_CHANNELS_ADD_ERROR,
  SETTINGS_SMS_CHANNELS_ADD,
  SETTINGS_SMS_CHANNELS_ADD_REMOVE_FAIL,
  SETTINGS_SMS_CHANNELS_ADD_REMOVE,
  SETTINGS_SMS_CHANNELS_ADD_REMOVE_SUCCESS,
  SETTINGS_SMS_CHANNELS_ADD_CLEANUP,
  SETTINGS_CHANNELS_FC_CONFIG_ADD_SUCCESS,
  SETTINGS_CHANNELS_FC_CONFIG_ADD,
  SETTINGS_CHANNELS_FC_CONFIG_ADD_CLEAN,
  SETTINGS_CHANNELS_FC_CONFIG_ADD_ERROR,
  SETTINGS_CHANNELS_DND_CONFIG_ADD_ERROR,
  SETTINGS_CHANNELS_DND_CONFIG_ADD_CLEAN,
  SETTINGS_CHANNELS_DND_CONFIG_ADD_SUCCESS,
  SETTINGS_CHANNELS_DND_CONFIG_ADD,
  SETTINGS_CHANNELS_FC_GET_SUCCESS,
  SETTINGS_CHANNELS_FC_GET,
  SETTINGS_CHANNELS_DND_GET,
  SETTINGS_CHANNELS_DND_GET_SUCCESS,
  SETTINGS_SMS_CHANNELS_EDIT,
  SETTINGS_SMS_CHANNELS_EDIT_SUCCESS,
  SETTINGS_EMAIL_CHANNELS_ADD,
  SETTINGS_EMAIL_CHANNELS_ADD_SUCCESS,
  SETTINGS_EMAIL_CHANNELS_ADD_ERROR,
  SETTINGS_EMAIL_CHANNELS_ADD_CLEANUP,
  SETTINGS_EMAIL_CHANNELS_EDIT,
  SETTINGS_EMAIL_CHANNELS_EDIT_SUCCESS,
  SETTINGS_EMAIL_CHANNELS_EDIT_ERROR,
  SETTINGS_EMAIL_CHANNELS_REMOVE,
  SETTINGS_EMAIL_CHANNELS_REMOVE_SUCCESS,
  SETTINGS_EMAIL_CHANNELS_REMOVE_FAIL,
  SETTINGS_WHATSAPP_CHANNELS_GET,
  SETTINGS_WHATSAPP_CHANNELS_ADD,
  SETTINGS_WHATSAPP_CHANNELS_ADD_SUCCESS,
  SETTINGS_WHATSAPP_CHANNELS_ADD_ERROR,
  SETTINGS_WHATSAPP_CHANNELS_ADD_CLEANUP,
  SETTINGS_WHATSAPP_CHANNELS_GET_SUCCESS,
  SETTINGS_WHATSAPP_CHANNELS_REMOVE,
  SETTINGS_WHATSAPP_CHANNELS_REMOVE_SUCCESS,
  SETTINGS_WHATSAPP_CHANNELS_REMOVE_ERROR,
  SETTINGS_WHATSAPP_CHANNELS_EDIT,
  SETTINGS_WHATSAPP_CHANNELS_EDIT_SUCCESS,
  COUNTRY_LIST_GET_SUCCESS,
  COUNTRY_LIST_GET,
  EMAIL_GENERAL_SETTINGS_ADD,
  EMAIL_GENERAL_SETTINGS_ADD_SUCCESS,
  EMAIL_GENERAL_SETTINGS_ADD_CLEAN,
  EMAIL_GENERAL_SETTINGS_ADD_ERROR,
  EMAIL_GENERAL_SETTINGS_GET,
  EMAIL_GENERAL_SETTINGS_GET_SUCCESS,
  SETTINGS_EMAIL_CHANNELS_GET,
  SETTINGS_EMAIL_CHANNELS_GET_SUCCESS,
} from 'redux/constants';
import { describe, it, expect } from '@jest/globals';

describe('Channels Actions', () => {
  const item = {};

  it.each([
    [actions.getSettingsSMSConnectorList, SETTINGS_SMS_CHANNELS_GET],
    [actions.getSettingsSMSSuccess, SETTINGS_SMS_CHANNELS_GET_SUCCESS],
    [actions.addChannelConnector, SETTINGS_SMS_CHANNELS_ADD],
    [actions.addChannelConnectorSuccess, SETTINGS_SMS_CHANNELS_ADD_SUCCESS],
    [actions.addChannelConnectorError, SETTINGS_SMS_CHANNELS_ADD_ERROR],
    [actions.addChannelConnectorClean, SETTINGS_SMS_CHANNELS_ADD_CLEANUP],
    [actions.removeChannelConnector, SETTINGS_SMS_CHANNELS_ADD_REMOVE],
    [
      actions.removeChannelConnectorSuccess,
      SETTINGS_SMS_CHANNELS_ADD_REMOVE_SUCCESS,
    ],
    [actions.removeChannelConnectorFail, SETTINGS_SMS_CHANNELS_ADD_REMOVE_FAIL],
    [actions.editChannelConnector, SETTINGS_SMS_CHANNELS_EDIT],
    [actions.editChannelConnectorSuccess, SETTINGS_SMS_CHANNELS_EDIT_SUCCESS],
    [actions.getEmailConnectorList, SETTINGS_EMAIL_CHANNELS_GET],
    [actions.getEmailConnectorListSuccess, SETTINGS_EMAIL_CHANNELS_GET_SUCCESS],
    [actions.addEmailConnector, SETTINGS_EMAIL_CHANNELS_ADD],
    [actions.addEmailConnectorSuccess, SETTINGS_EMAIL_CHANNELS_ADD_SUCCESS],
    [actions.addEmailConnectorError, SETTINGS_EMAIL_CHANNELS_ADD_ERROR],
    [actions.addEmailConnectorClean, SETTINGS_EMAIL_CHANNELS_ADD_CLEANUP],
    [actions.editEmailConnector, SETTINGS_EMAIL_CHANNELS_EDIT],
    [actions.editEmailConnectorSuccess, SETTINGS_EMAIL_CHANNELS_EDIT_SUCCESS],
    [actions.editEmailConnectorError, SETTINGS_EMAIL_CHANNELS_EDIT_ERROR],
    [actions.removeEmailConnector, SETTINGS_EMAIL_CHANNELS_REMOVE],
    [
      actions.removeEmailConnectorSuccess,
      SETTINGS_EMAIL_CHANNELS_REMOVE_SUCCESS,
    ],
    [actions.removeEmailConnectorFail, SETTINGS_EMAIL_CHANNELS_REMOVE_FAIL],
    [actions.addEmailGeneralSettings, EMAIL_GENERAL_SETTINGS_ADD],
    [
      actions.addEmailGeneralSettingsSuccess,
      EMAIL_GENERAL_SETTINGS_ADD_SUCCESS,
    ],
    [actions.addEmailGeneralSettingsClean, EMAIL_GENERAL_SETTINGS_ADD_CLEAN],
    [actions.addEmailGeneralSettingsError, EMAIL_GENERAL_SETTINGS_ADD_ERROR],
    [actions.getEmailGeneralSettingsList, EMAIL_GENERAL_SETTINGS_GET],
    [
      actions.getEmailGeneralSettingsListSuccess,
      EMAIL_GENERAL_SETTINGS_GET_SUCCESS,
    ],
    [actions.addFreqCappingConfig, SETTINGS_CHANNELS_FC_CONFIG_ADD],
    [
      actions.addFreqCappingConfigSuccess,
      SETTINGS_CHANNELS_FC_CONFIG_ADD_SUCCESS,
    ],
    [actions.addFreqCappingConfigClean, SETTINGS_CHANNELS_FC_CONFIG_ADD_CLEAN],
    [actions.addFreqCappingConfigError, SETTINGS_CHANNELS_FC_CONFIG_ADD_ERROR],
    [actions.getSettingsFCList, SETTINGS_CHANNELS_FC_GET],
    [actions.getSettingsFCListSuccess, SETTINGS_CHANNELS_FC_GET_SUCCESS],
    [actions.addDnDConfig, SETTINGS_CHANNELS_DND_CONFIG_ADD],
    [actions.addDnDConfigSuccess, SETTINGS_CHANNELS_DND_CONFIG_ADD_SUCCESS],
    [actions.addDnDConfigClean, SETTINGS_CHANNELS_DND_CONFIG_ADD_CLEAN],
    [actions.addDnDConfigError, SETTINGS_CHANNELS_DND_CONFIG_ADD_ERROR],
    [actions.getSettingsDnDList, SETTINGS_CHANNELS_DND_GET],
    [actions.getSettingsDnDListSuccess, SETTINGS_CHANNELS_DND_GET_SUCCESS],
    [actions.getSettingsWhatsAppConnectorList, SETTINGS_WHATSAPP_CHANNELS_GET],
    [
      actions.getSettingsWhatsAppConnectorListSuccess,
      SETTINGS_WHATSAPP_CHANNELS_GET_SUCCESS,
    ],
    [actions.addWhatsAppChannelConnector, SETTINGS_WHATSAPP_CHANNELS_ADD],
    [
      actions.addWhatsAppChannelConnectorSuccess,
      SETTINGS_WHATSAPP_CHANNELS_ADD_SUCCESS,
    ],
    [
      actions.addWhatsAppChannelConnectorError,
      SETTINGS_WHATSAPP_CHANNELS_ADD_ERROR,
    ],
    [
      actions.addWhatsAppChannelConnectorClean,
      SETTINGS_WHATSAPP_CHANNELS_ADD_CLEANUP,
    ],
    [actions.removeWhatsAppChannelConnector, SETTINGS_WHATSAPP_CHANNELS_REMOVE],
    [
      actions.removeWhatsAppChannelConnectorSuccess,
      SETTINGS_WHATSAPP_CHANNELS_REMOVE_SUCCESS,
    ],
    [
      actions.removeWhatsAppChannelConnectorError,
      SETTINGS_WHATSAPP_CHANNELS_REMOVE_ERROR,
    ],
    [actions.editWhatsAppChannelConnector, SETTINGS_WHATSAPP_CHANNELS_EDIT],
    [
      actions.editWhatsAppChannelConnectorSuccess,
      SETTINGS_WHATSAPP_CHANNELS_EDIT_SUCCESS,
    ],
    [actions.getCountryDropdownList, COUNTRY_LIST_GET],
    [actions.getCountryDropdownListSuccess, COUNTRY_LIST_GET_SUCCESS],
  ])('should create %p action', (actionCreator, expectedType) => {
    expect(actionCreator(item)).toEqual({
      type: expectedType,
      payload: item,
    });
  });
});
