const ContactsEnums = Object.freeze({
  STANDARD: 'standard',
  NAME: 'name',
  EMAIL: 'email',
  PHONE_NUMBER: 'phone_number',
  IDENTIFIER: 'identifier',
  COUNTRY: 'country_code',
  CITY: 'city',
  LAST_ACTIVITY: 'last_activity_at',
  CREATED_AT: 'created_at',
  EQUAL_TO: 'equal_to',
  NOT_EQUAL_TO: 'not_equal_to',
  AND: 'and',
  OR: 'or',
  GREATER_THAN: 'is_greater_than',
  LESSER_THAN: 'is_less_than',
  IS_X_DAYS: 'days_before',
  ATTRIBUTE_CONTACT: 'contact_attribute',
  TEXT: 'text',
  DATE: 'date',
  NUMBER: 'number',
  CUSTOM_ATTRIBUTES: 'Custom Attributes',
  CONTAINS: 'contains',
  DOES_NOT_CONTAIN: 'does_not_contain',
  PRESENT: 'is_present',
  NOT_PRESENT: 'is_not_present',
  PLUS_ICON: '+',
  CUSTOM_VIEW: 'custom_view',
  CONTACT: 'contact',
  ACTIVE: 'active',
  FILTER_KEYS: {
    STATUS: 'status',
    EQUALS_TO: 'equal_to',
    STANDARD: 'standard',
    ADDITIONAL_ATTRIBUTES: 'additional_attributes',
    TEXT: 'text',
    MULTI_SELECT: 'multi_select',
  },
  ALL: 'all',
  OBJECT: 'object',
});

export default ContactsEnums;
