const createSegementEnums = Object.freeze({
  INITIALVALUES: {
    TRUE: 'true',
    FILTER_BY_USERS: 'filterByUsers',
    ALL_USERS: 'all_users',
    OR: 'or',
    AND: 'and',
    NESTED_FILTERS: 'nested_filters',
    DIGO_ALL_USERS: 'digo_all_users',
    EXCLUDED_FILTERS: 'excluded_filters',
    INCLUDED_FILTERS: 'included_filters',
    FILTERS: 'filters',
    SELECT_AUDIENCE: 'audience_type',
    EXCLUDE_FILTERS: 'exclude_users',
    USER_AFFINITY_ATTRIBUTES: 'user_affinity_attributes',
    USER_BEHAVIOR_ATTRIBUTES: 'user_behavior_attributes',
  },
  CONDITION: {
    TRUE: 'true',
    FALSE: 'false',
    FILTER_BY_USERS: 'filterByUsers',
    ALL_USERS: 'allUsers',
    AND: 'and',
    OR: 'or',
    OBJECT: 'object',
    STRING: 'string',
    NUMBER: 'number',
    HAS_EXECUTED: 'Has Executed',
    USER_PROPERTY: 'user_property',
    USER_BEHAVIOR: 'user_behavior',
    USER_AFFINITY: 'user_affinity',
    CUSTOM_SEGMENT: 'custom_segments',
    DATE_TIME: 'datetime',
    DOUBLE: 'double',
    BOOLEAN: 'boolean',
    ARRAY_STRING: 'array_string',
    DATE: 'date',
    YEARLY_WHERE_THE_DATE: 'yearly_where_the_date',
    YEARLY_WHERE_THE_MONTH: 'yearly_where_the_month',
    DAILY_WHERE_THE_HOUR: 'daily_where_the_hour',
    IS_BETWEEN: 'is_between',
    IN_THE_FOLLOWING: 'in_the_following',
    PREDOMINANTLY: 'predominantly',
    FOR_MIN_OF: 'for_a_minimum_of',
    MOST_OF_TIMES: 'most_no_of_times',
    LEAST_NO_OF_TIMES: 'least_no_of_times',
    ALL_SEGMENTS: 'all-segments',
    IN_THE_LAST: 'in_the_last',
    IN_BETWEEN: 'in_between',
    BEFORE: 'before',
    ON: 'on',
    AFTER: 'after',
    TODAY: 'today',
    YESTERDAY: 'yesterday',
    THIS_WEEK: 'this_week',
    LAST_WEEK: 'last_week',
    THIS_MONTH: 'this_month',
    LAST_MONTH: 'last_month',
    NULL: 'NULL',
    DAYS: 'days',
    DAYS_AGO: 'days_ago',
    USER_AFFINITY_COND: 'userAffinity',
    USER_BEHAVIOR_COND: 'userBehavior',
    WITH: 'with',
    WITH_ATTRIBUTE: 'with attribute',
    PERCENT_OF_TIMES: '% of the times',
    AND_FILTER_TOP: 'and filter top',
    PERCENT_OF_THE_USERS: '% of the users',
    AND_FILTER_BOTTOM: 'and filter bottom',
    HAS_EXITED: 'Has Exited',
    IS: 'is',
  },
  LABEL: {
    ALL_USERS: 'All Users',
    SELECT_OPERATOR: 'Select Operator',
    CASE_SENSITIVE: 'Case Sensitive',
    CASE_IN_SENSITIVE: 'Case Insensitive',
    DATE_SHOULD_BE_GREATER:
      'The date should be later than the date in the previous field',
    DAYS_SHOULD_BE_LESS_THAN: 'Start days should be less than end days',
    NO_NEGATIVE_VALUES: 'No negative values allowed',
    PERCENT_VALIDATION: 'Percent value should be less than 100',
  },
  IDENTIFIERS: {
    NAME: 'name',
    OPERATOR: 'operator',
    DISPLAYED_NAME: 'displayed_name',
    OPERATOR_TYPE: 'operator_type',
    DATA_TYPE: 'data_type',
    RANGE: 'range',
    ATTRIBUTES: 'attributes',
    PRIMARY_TIME_RANGE: 'primary_time_range',
    UN_GROUPED: 'unGrouped',
    GROUPED: 'grouped',
    VALUE: 'value',
    VALUE1: 'value1',
    CASE_SENSITIVE: 'case_sensitive',
    CASE_IN_SENSITIVE: 'case insensitive',
  },
  CATEGORY: {
    CUSTOM_ATTRIBUTES: 'Custom Attributes',
  },
  DATA_TYPE: {
    BOOLEAN: 'boolean',
    STRING: 'string',
    DATE: 'date',
    NUMBER: 'number',
  },
  RANGE_CONSTANTS: {
    YEAR_RANGE: 365,
    WEEK_RANGE: 7,
    MONTH_RANGE: 12,
    DAYS_RANGE: 31,
    OTHER_RANGE: 600,
  },
});

export default createSegementEnums;
